### ISSUE TITLE
Add support for RetroArch

### ISSUE THREAD

**Issue by Tabaluga** [cosmo0/retropie-overlays#10]
Dear @cosmo0 ,
I'm using your *Console overlays set* for RetroPie, which uses RetroArch as base.
Is it possible that you could add support for RetroArch for your *Console overlays set*, or perhaps add instructions how I can convert your *RetroPie set* to a *RetroArch set*?
Best regards

**Comment by cosmo0** [comment]
Hey! Sorry for the delay.

Retropie, Recalbox and Batocera are all based on RetroArch, they just use specific configurations.

You'll have to find out where the config files must be located in your RA version, copy the proper config files there, and edit the paths to match your installation.

Sorry I can't help you much more, I don't use RA on a PC so I don't even know where to look for the info.
