### ISSUE TITLE
GBA picture

### ISSUE THREAD

**Issue by the-real-dje33** [cosmo0/retropie-overlays#3]
L'image est décalé sur les overlay GBA
Voici les paramètres pour recaler l'image.

# 1080p
custom_viewport_width = "1280"
custom_viewport_height = "836"
custom_viewport_x = "321"
custom_viewport_y = "101"

**Comment by cosmo0** [comment]
En effet, en fait la GBA était pétée et il manquait quelques pixels en bas et à droite. J'ai tout corrigé normalement.
