### ISSUE TITLE
Recalbox overlays

### ISSUE THREAD

**Issue by djibux** [cosmo0/retropie-overlays#7]
Hello,
I would be interested in a package for recalbox if you think you can make one.

**Comment by cosmo0** [comment]
Added additional systems:

- Amiga CD32: ok
- Atomiswave: ok
- Naomi: ok
- NeoGeo CD: ok
- PC Engine CD: ok
- Stellaview: ok

Doing the rest of the config.

**Comment by cosmo0** [comment]
ok all done

**Comment by cosmo0** [comment]
@djibux I'm sure you forgot this issue even existed heh? lol

**Comment by djibux** [comment]
Nope, I remember ;)

I’m eager to try it out!
Thanks a lot.

**Comment by cosmo0** [comment]
That being said, in the meantime Recalbox has made their own pack: https://forum.recalbox.com/topic/22321/recalbox-7-x-overlays-complets

**Comment by djibux** [comment]
Works like a charm, thanks.  Maybe you should just mention to copy the files within `overlays_recalbox` and not the folder itself.
Thanks!

**Comment by cosmo0** [comment]
Right! Thanks for the feedback :)
