### ISSUE TITLE
Screen size not matching viewport.

### ISSUE THREAD

**Issue by LordPinkerton** [cosmo0/retropie-overlays#8]
I'm not certain what's going on, but I followed the install directions precisely. I downloaded the shader overlay latest release and copied it into my RetroPie's /opt/retropie/config/ directory, overriding the files asked. However, every game I play, the game screen is not being shrunk to fit the viewport, so a ton of the game is being clipped off by the overlay. I did backup my folder so it's not hard to reverse it, but I would still like to get this working correctly.

**Comment by rexeven** [comment]
I'm having the same issue, but only with Game Gear and GBA. And everything is fresh and just reflashed/updated. Let me know what I can provide to help diagnose!

**Comment by cosmo0** [comment]
Just checked all systems in the new release (V1.3), everything should work.

It now works with a 1080p resolution every time. It seems I don't have control of resolution from the overlay configs in the latest Retropie versions, maybe that was the source of your problems.
